name: Build Executable

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests

    - name: Build Windows executable
      run: |
        pyinstaller --onefile --icon=Assets/app.ico --add-data "Assets:Assets" Webhooker.py

    - name: Upload Windows executable artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows-Build
        path: dist/Webhooker.exe

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests

    - name: Build Linux executable
      run: |
        pyinstaller --onefile --icon=Assets/app.ico --add-data "Assets:Assets" Webhooker.py

    - name: Upload Linux executable artifact
      uses: actions/upload-artifact@v2
      with:
        name: Linux-Build
        path: dist/Webhooker